# Makefile.in generated by automake 1.10.2 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/tortunnel
pkglibdir = $(libdir)/tortunnel
pkgincludedir = $(includedir)/tortunnel
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = torproxy$(EXEEXT) torscanner$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_torproxy_OBJECTS = TorProxy.$(OBJEXT) HybridEncryption.$(OBJEXT) \
	Connection.$(OBJEXT) Cell.$(OBJEXT) Directory.$(OBJEXT) \
	ServerListing.$(OBJEXT) Util.$(OBJEXT) Circuit.$(OBJEXT) \
	CellEncrypter.$(OBJEXT) RelayCellDispatcher.$(OBJEXT) \
	CellConsumer.$(OBJEXT) ProxyShuffler.$(OBJEXT) \
	CreateCell.$(OBJEXT) CreatedCell.$(OBJEXT) TorTunnel.$(OBJEXT) \
	SocksConnection.$(OBJEXT) Network.$(OBJEXT)
torproxy_OBJECTS = $(am_torproxy_OBJECTS)
torproxy_LDADD = $(LDADD)
torproxy_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(torproxy_LDFLAGS) $(LDFLAGS) -o $@
am_torscanner_OBJECTS = TorScanner.$(OBJEXT) \
	HybridEncryption.$(OBJEXT) Connection.$(OBJEXT) Cell.$(OBJEXT) \
	Directory.$(OBJEXT) ServerListing.$(OBJEXT) Util.$(OBJEXT) \
	Circuit.$(OBJEXT) CellEncrypter.$(OBJEXT) \
	RelayCellDispatcher.$(OBJEXT) CellConsumer.$(OBJEXT) \
	ProxyShuffler.$(OBJEXT) CreateCell.$(OBJEXT) \
	CreatedCell.$(OBJEXT) TorTunnel.$(OBJEXT) Network.$(OBJEXT) \
	ServerListingGroup.$(OBJEXT)
torscanner_OBJECTS = $(am_torscanner_OBJECTS)
torscanner_LDADD = $(LDADD)
torscanner_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(torscanner_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(torproxy_SOURCES) $(torscanner_SOURCES)
DIST_SOURCES = $(torproxy_SOURCES) $(torscanner_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/carlos/Git/tortunnel/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/carlos/Git/tortunnel/missing --run tar
AUTOCONF = ${SHELL} /home/carlos/Git/tortunnel/missing --run autoconf
AUTOHEADER = ${SHELL} /home/carlos/Git/tortunnel/missing --run autoheader
AUTOMAKE = ${SHELL} /home/carlos/Git/tortunnel/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/carlos/Git/tortunnel/missing --run makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = tortunnel
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.3
abs_builddir = /home/carlos/Git/tortunnel
abs_srcdir = /home/carlos/Git/tortunnel
abs_top_builddir = /home/carlos/Git/tortunnel
abs_top_srcdir = /home/carlos/Git/tortunnel
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/carlos/Git/tortunnel/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /usr/bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CXXFLAGS = -ggdb
torproxy_SOURCES = TorProxy.cpp TorProxy.h ShuffleStream.h protocol/RelayCellDispatcher.h protocol/HybridEncryption.h protocol/HybridEncryption.cpp protocol/Connection.cpp protocol/Connection.h protocol/Cell.cpp protocol/Cell.h protocol/Directory.cpp protocol/Directory.h protocol/RelayDataCell.h protocol/CreatedCell.h protocol/RelayCell.h protocol/RelayEndCell.h protocol/RelaySendMeCell.h protocol/ServerListing.cpp protocol/ServerListing.h util/Util.cpp protocol/Circuit.cpp protocol/Circuit.h protocol/CellEncrypter.cpp protocol/CellEncrypter.h protocol/RelayBeginCell.h protocol/CellListener.h protocol/RelayCellDispatcher.cpp protocol/CellConsumer.cpp protocol/CellConsumer.h ProxyShuffler.cpp protocol/CreateCell.cpp protocol/CreateCell.h protocol/CreatedCell.cpp TorTunnel.cpp TorTunnel.h SocksConnection.cpp SocksConnection.h util/Network.cpp ProxyShuffler.h util/Network.h util/Util.h
torproxy_LDFLAGS = -lssl -lboost_system-mt
torscanner_SOURCES = TorScanner.cpp TorScanner.h ShuffleStream.h protocol/RelayCellDispatcher.h protocol/HybridEncryption.h protocol/HybridEncryption.cpp protocol/Connection.cpp protocol/Connection.h protocol/Cell.cpp protocol/Cell.h protocol/Directory.cpp protocol/Directory.h protocol/RelayDataCell.h protocol/CreatedCell.h protocol/RelayCell.h protocol/RelayEndCell.h protocol/RelaySendMeCell.h protocol/ServerListing.cpp protocol/ServerListing.h util/Util.cpp protocol/Circuit.cpp protocol/Circuit.h protocol/CellEncrypter.cpp protocol/CellEncrypter.h protocol/RelayBeginCell.h protocol/CellListener.h protocol/RelayCellDispatcher.cpp protocol/CellConsumer.cpp protocol/CellConsumer.h ProxyShuffler.cpp protocol/CreateCell.cpp protocol/CreateCell.h protocol/CreatedCell.cpp TorTunnel.cpp TorTunnel.h util/Network.cpp protocol/ServerListingGroup.cpp protocol/ServerListingGroup.h util/Network.h util/Util.h
torscanner_LDFLAGS = -lssl -lboost_system-mt
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
torproxy$(EXEEXT): $(torproxy_OBJECTS) $(torproxy_DEPENDENCIES) 
	@rm -f torproxy$(EXEEXT)
	$(torproxy_LINK) $(torproxy_OBJECTS) $(torproxy_LDADD) $(LIBS)
torscanner$(EXEEXT): $(torscanner_OBJECTS) $(torscanner_DEPENDENCIES) 
	@rm -f torscanner$(EXEEXT)
	$(torscanner_LINK) $(torscanner_OBJECTS) $(torscanner_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/Cell.Po
include ./$(DEPDIR)/CellConsumer.Po
include ./$(DEPDIR)/CellEncrypter.Po
include ./$(DEPDIR)/Circuit.Po
include ./$(DEPDIR)/Connection.Po
include ./$(DEPDIR)/CreateCell.Po
include ./$(DEPDIR)/CreatedCell.Po
include ./$(DEPDIR)/Directory.Po
include ./$(DEPDIR)/HybridEncryption.Po
include ./$(DEPDIR)/Network.Po
include ./$(DEPDIR)/ProxyShuffler.Po
include ./$(DEPDIR)/RelayCellDispatcher.Po
include ./$(DEPDIR)/ServerListing.Po
include ./$(DEPDIR)/ServerListingGroup.Po
include ./$(DEPDIR)/SocksConnection.Po
include ./$(DEPDIR)/TorProxy.Po
include ./$(DEPDIR)/TorScanner.Po
include ./$(DEPDIR)/TorTunnel.Po
include ./$(DEPDIR)/Util.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

HybridEncryption.o: protocol/HybridEncryption.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HybridEncryption.o -MD -MP -MF $(DEPDIR)/HybridEncryption.Tpo -c -o HybridEncryption.o `test -f 'protocol/HybridEncryption.cpp' || echo '$(srcdir)/'`protocol/HybridEncryption.cpp
	mv -f $(DEPDIR)/HybridEncryption.Tpo $(DEPDIR)/HybridEncryption.Po
#	source='protocol/HybridEncryption.cpp' object='HybridEncryption.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HybridEncryption.o `test -f 'protocol/HybridEncryption.cpp' || echo '$(srcdir)/'`protocol/HybridEncryption.cpp

HybridEncryption.obj: protocol/HybridEncryption.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HybridEncryption.obj -MD -MP -MF $(DEPDIR)/HybridEncryption.Tpo -c -o HybridEncryption.obj `if test -f 'protocol/HybridEncryption.cpp'; then $(CYGPATH_W) 'protocol/HybridEncryption.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/HybridEncryption.cpp'; fi`
	mv -f $(DEPDIR)/HybridEncryption.Tpo $(DEPDIR)/HybridEncryption.Po
#	source='protocol/HybridEncryption.cpp' object='HybridEncryption.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HybridEncryption.obj `if test -f 'protocol/HybridEncryption.cpp'; then $(CYGPATH_W) 'protocol/HybridEncryption.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/HybridEncryption.cpp'; fi`

Connection.o: protocol/Connection.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Connection.o -MD -MP -MF $(DEPDIR)/Connection.Tpo -c -o Connection.o `test -f 'protocol/Connection.cpp' || echo '$(srcdir)/'`protocol/Connection.cpp
	mv -f $(DEPDIR)/Connection.Tpo $(DEPDIR)/Connection.Po
#	source='protocol/Connection.cpp' object='Connection.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Connection.o `test -f 'protocol/Connection.cpp' || echo '$(srcdir)/'`protocol/Connection.cpp

Connection.obj: protocol/Connection.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Connection.obj -MD -MP -MF $(DEPDIR)/Connection.Tpo -c -o Connection.obj `if test -f 'protocol/Connection.cpp'; then $(CYGPATH_W) 'protocol/Connection.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Connection.cpp'; fi`
	mv -f $(DEPDIR)/Connection.Tpo $(DEPDIR)/Connection.Po
#	source='protocol/Connection.cpp' object='Connection.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Connection.obj `if test -f 'protocol/Connection.cpp'; then $(CYGPATH_W) 'protocol/Connection.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Connection.cpp'; fi`

Cell.o: protocol/Cell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Cell.o -MD -MP -MF $(DEPDIR)/Cell.Tpo -c -o Cell.o `test -f 'protocol/Cell.cpp' || echo '$(srcdir)/'`protocol/Cell.cpp
	mv -f $(DEPDIR)/Cell.Tpo $(DEPDIR)/Cell.Po
#	source='protocol/Cell.cpp' object='Cell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Cell.o `test -f 'protocol/Cell.cpp' || echo '$(srcdir)/'`protocol/Cell.cpp

Cell.obj: protocol/Cell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Cell.obj -MD -MP -MF $(DEPDIR)/Cell.Tpo -c -o Cell.obj `if test -f 'protocol/Cell.cpp'; then $(CYGPATH_W) 'protocol/Cell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Cell.cpp'; fi`
	mv -f $(DEPDIR)/Cell.Tpo $(DEPDIR)/Cell.Po
#	source='protocol/Cell.cpp' object='Cell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Cell.obj `if test -f 'protocol/Cell.cpp'; then $(CYGPATH_W) 'protocol/Cell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Cell.cpp'; fi`

Directory.o: protocol/Directory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Directory.o -MD -MP -MF $(DEPDIR)/Directory.Tpo -c -o Directory.o `test -f 'protocol/Directory.cpp' || echo '$(srcdir)/'`protocol/Directory.cpp
	mv -f $(DEPDIR)/Directory.Tpo $(DEPDIR)/Directory.Po
#	source='protocol/Directory.cpp' object='Directory.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Directory.o `test -f 'protocol/Directory.cpp' || echo '$(srcdir)/'`protocol/Directory.cpp

Directory.obj: protocol/Directory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Directory.obj -MD -MP -MF $(DEPDIR)/Directory.Tpo -c -o Directory.obj `if test -f 'protocol/Directory.cpp'; then $(CYGPATH_W) 'protocol/Directory.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Directory.cpp'; fi`
	mv -f $(DEPDIR)/Directory.Tpo $(DEPDIR)/Directory.Po
#	source='protocol/Directory.cpp' object='Directory.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Directory.obj `if test -f 'protocol/Directory.cpp'; then $(CYGPATH_W) 'protocol/Directory.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Directory.cpp'; fi`

ServerListing.o: protocol/ServerListing.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ServerListing.o -MD -MP -MF $(DEPDIR)/ServerListing.Tpo -c -o ServerListing.o `test -f 'protocol/ServerListing.cpp' || echo '$(srcdir)/'`protocol/ServerListing.cpp
	mv -f $(DEPDIR)/ServerListing.Tpo $(DEPDIR)/ServerListing.Po
#	source='protocol/ServerListing.cpp' object='ServerListing.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ServerListing.o `test -f 'protocol/ServerListing.cpp' || echo '$(srcdir)/'`protocol/ServerListing.cpp

ServerListing.obj: protocol/ServerListing.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ServerListing.obj -MD -MP -MF $(DEPDIR)/ServerListing.Tpo -c -o ServerListing.obj `if test -f 'protocol/ServerListing.cpp'; then $(CYGPATH_W) 'protocol/ServerListing.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/ServerListing.cpp'; fi`
	mv -f $(DEPDIR)/ServerListing.Tpo $(DEPDIR)/ServerListing.Po
#	source='protocol/ServerListing.cpp' object='ServerListing.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ServerListing.obj `if test -f 'protocol/ServerListing.cpp'; then $(CYGPATH_W) 'protocol/ServerListing.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/ServerListing.cpp'; fi`

Util.o: util/Util.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Util.o -MD -MP -MF $(DEPDIR)/Util.Tpo -c -o Util.o `test -f 'util/Util.cpp' || echo '$(srcdir)/'`util/Util.cpp
	mv -f $(DEPDIR)/Util.Tpo $(DEPDIR)/Util.Po
#	source='util/Util.cpp' object='Util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Util.o `test -f 'util/Util.cpp' || echo '$(srcdir)/'`util/Util.cpp

Util.obj: util/Util.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Util.obj -MD -MP -MF $(DEPDIR)/Util.Tpo -c -o Util.obj `if test -f 'util/Util.cpp'; then $(CYGPATH_W) 'util/Util.cpp'; else $(CYGPATH_W) '$(srcdir)/util/Util.cpp'; fi`
	mv -f $(DEPDIR)/Util.Tpo $(DEPDIR)/Util.Po
#	source='util/Util.cpp' object='Util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Util.obj `if test -f 'util/Util.cpp'; then $(CYGPATH_W) 'util/Util.cpp'; else $(CYGPATH_W) '$(srcdir)/util/Util.cpp'; fi`

Circuit.o: protocol/Circuit.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Circuit.o -MD -MP -MF $(DEPDIR)/Circuit.Tpo -c -o Circuit.o `test -f 'protocol/Circuit.cpp' || echo '$(srcdir)/'`protocol/Circuit.cpp
	mv -f $(DEPDIR)/Circuit.Tpo $(DEPDIR)/Circuit.Po
#	source='protocol/Circuit.cpp' object='Circuit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Circuit.o `test -f 'protocol/Circuit.cpp' || echo '$(srcdir)/'`protocol/Circuit.cpp

Circuit.obj: protocol/Circuit.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Circuit.obj -MD -MP -MF $(DEPDIR)/Circuit.Tpo -c -o Circuit.obj `if test -f 'protocol/Circuit.cpp'; then $(CYGPATH_W) 'protocol/Circuit.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Circuit.cpp'; fi`
	mv -f $(DEPDIR)/Circuit.Tpo $(DEPDIR)/Circuit.Po
#	source='protocol/Circuit.cpp' object='Circuit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Circuit.obj `if test -f 'protocol/Circuit.cpp'; then $(CYGPATH_W) 'protocol/Circuit.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/Circuit.cpp'; fi`

CellEncrypter.o: protocol/CellEncrypter.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CellEncrypter.o -MD -MP -MF $(DEPDIR)/CellEncrypter.Tpo -c -o CellEncrypter.o `test -f 'protocol/CellEncrypter.cpp' || echo '$(srcdir)/'`protocol/CellEncrypter.cpp
	mv -f $(DEPDIR)/CellEncrypter.Tpo $(DEPDIR)/CellEncrypter.Po
#	source='protocol/CellEncrypter.cpp' object='CellEncrypter.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CellEncrypter.o `test -f 'protocol/CellEncrypter.cpp' || echo '$(srcdir)/'`protocol/CellEncrypter.cpp

CellEncrypter.obj: protocol/CellEncrypter.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CellEncrypter.obj -MD -MP -MF $(DEPDIR)/CellEncrypter.Tpo -c -o CellEncrypter.obj `if test -f 'protocol/CellEncrypter.cpp'; then $(CYGPATH_W) 'protocol/CellEncrypter.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CellEncrypter.cpp'; fi`
	mv -f $(DEPDIR)/CellEncrypter.Tpo $(DEPDIR)/CellEncrypter.Po
#	source='protocol/CellEncrypter.cpp' object='CellEncrypter.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CellEncrypter.obj `if test -f 'protocol/CellEncrypter.cpp'; then $(CYGPATH_W) 'protocol/CellEncrypter.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CellEncrypter.cpp'; fi`

RelayCellDispatcher.o: protocol/RelayCellDispatcher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RelayCellDispatcher.o -MD -MP -MF $(DEPDIR)/RelayCellDispatcher.Tpo -c -o RelayCellDispatcher.o `test -f 'protocol/RelayCellDispatcher.cpp' || echo '$(srcdir)/'`protocol/RelayCellDispatcher.cpp
	mv -f $(DEPDIR)/RelayCellDispatcher.Tpo $(DEPDIR)/RelayCellDispatcher.Po
#	source='protocol/RelayCellDispatcher.cpp' object='RelayCellDispatcher.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RelayCellDispatcher.o `test -f 'protocol/RelayCellDispatcher.cpp' || echo '$(srcdir)/'`protocol/RelayCellDispatcher.cpp

RelayCellDispatcher.obj: protocol/RelayCellDispatcher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RelayCellDispatcher.obj -MD -MP -MF $(DEPDIR)/RelayCellDispatcher.Tpo -c -o RelayCellDispatcher.obj `if test -f 'protocol/RelayCellDispatcher.cpp'; then $(CYGPATH_W) 'protocol/RelayCellDispatcher.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/RelayCellDispatcher.cpp'; fi`
	mv -f $(DEPDIR)/RelayCellDispatcher.Tpo $(DEPDIR)/RelayCellDispatcher.Po
#	source='protocol/RelayCellDispatcher.cpp' object='RelayCellDispatcher.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RelayCellDispatcher.obj `if test -f 'protocol/RelayCellDispatcher.cpp'; then $(CYGPATH_W) 'protocol/RelayCellDispatcher.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/RelayCellDispatcher.cpp'; fi`

CellConsumer.o: protocol/CellConsumer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CellConsumer.o -MD -MP -MF $(DEPDIR)/CellConsumer.Tpo -c -o CellConsumer.o `test -f 'protocol/CellConsumer.cpp' || echo '$(srcdir)/'`protocol/CellConsumer.cpp
	mv -f $(DEPDIR)/CellConsumer.Tpo $(DEPDIR)/CellConsumer.Po
#	source='protocol/CellConsumer.cpp' object='CellConsumer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CellConsumer.o `test -f 'protocol/CellConsumer.cpp' || echo '$(srcdir)/'`protocol/CellConsumer.cpp

CellConsumer.obj: protocol/CellConsumer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CellConsumer.obj -MD -MP -MF $(DEPDIR)/CellConsumer.Tpo -c -o CellConsumer.obj `if test -f 'protocol/CellConsumer.cpp'; then $(CYGPATH_W) 'protocol/CellConsumer.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CellConsumer.cpp'; fi`
	mv -f $(DEPDIR)/CellConsumer.Tpo $(DEPDIR)/CellConsumer.Po
#	source='protocol/CellConsumer.cpp' object='CellConsumer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CellConsumer.obj `if test -f 'protocol/CellConsumer.cpp'; then $(CYGPATH_W) 'protocol/CellConsumer.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CellConsumer.cpp'; fi`

CreateCell.o: protocol/CreateCell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CreateCell.o -MD -MP -MF $(DEPDIR)/CreateCell.Tpo -c -o CreateCell.o `test -f 'protocol/CreateCell.cpp' || echo '$(srcdir)/'`protocol/CreateCell.cpp
	mv -f $(DEPDIR)/CreateCell.Tpo $(DEPDIR)/CreateCell.Po
#	source='protocol/CreateCell.cpp' object='CreateCell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CreateCell.o `test -f 'protocol/CreateCell.cpp' || echo '$(srcdir)/'`protocol/CreateCell.cpp

CreateCell.obj: protocol/CreateCell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CreateCell.obj -MD -MP -MF $(DEPDIR)/CreateCell.Tpo -c -o CreateCell.obj `if test -f 'protocol/CreateCell.cpp'; then $(CYGPATH_W) 'protocol/CreateCell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CreateCell.cpp'; fi`
	mv -f $(DEPDIR)/CreateCell.Tpo $(DEPDIR)/CreateCell.Po
#	source='protocol/CreateCell.cpp' object='CreateCell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CreateCell.obj `if test -f 'protocol/CreateCell.cpp'; then $(CYGPATH_W) 'protocol/CreateCell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CreateCell.cpp'; fi`

CreatedCell.o: protocol/CreatedCell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CreatedCell.o -MD -MP -MF $(DEPDIR)/CreatedCell.Tpo -c -o CreatedCell.o `test -f 'protocol/CreatedCell.cpp' || echo '$(srcdir)/'`protocol/CreatedCell.cpp
	mv -f $(DEPDIR)/CreatedCell.Tpo $(DEPDIR)/CreatedCell.Po
#	source='protocol/CreatedCell.cpp' object='CreatedCell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CreatedCell.o `test -f 'protocol/CreatedCell.cpp' || echo '$(srcdir)/'`protocol/CreatedCell.cpp

CreatedCell.obj: protocol/CreatedCell.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CreatedCell.obj -MD -MP -MF $(DEPDIR)/CreatedCell.Tpo -c -o CreatedCell.obj `if test -f 'protocol/CreatedCell.cpp'; then $(CYGPATH_W) 'protocol/CreatedCell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CreatedCell.cpp'; fi`
	mv -f $(DEPDIR)/CreatedCell.Tpo $(DEPDIR)/CreatedCell.Po
#	source='protocol/CreatedCell.cpp' object='CreatedCell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CreatedCell.obj `if test -f 'protocol/CreatedCell.cpp'; then $(CYGPATH_W) 'protocol/CreatedCell.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/CreatedCell.cpp'; fi`

Network.o: util/Network.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Network.o -MD -MP -MF $(DEPDIR)/Network.Tpo -c -o Network.o `test -f 'util/Network.cpp' || echo '$(srcdir)/'`util/Network.cpp
	mv -f $(DEPDIR)/Network.Tpo $(DEPDIR)/Network.Po
#	source='util/Network.cpp' object='Network.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Network.o `test -f 'util/Network.cpp' || echo '$(srcdir)/'`util/Network.cpp

Network.obj: util/Network.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Network.obj -MD -MP -MF $(DEPDIR)/Network.Tpo -c -o Network.obj `if test -f 'util/Network.cpp'; then $(CYGPATH_W) 'util/Network.cpp'; else $(CYGPATH_W) '$(srcdir)/util/Network.cpp'; fi`
	mv -f $(DEPDIR)/Network.Tpo $(DEPDIR)/Network.Po
#	source='util/Network.cpp' object='Network.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Network.obj `if test -f 'util/Network.cpp'; then $(CYGPATH_W) 'util/Network.cpp'; else $(CYGPATH_W) '$(srcdir)/util/Network.cpp'; fi`

ServerListingGroup.o: protocol/ServerListingGroup.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ServerListingGroup.o -MD -MP -MF $(DEPDIR)/ServerListingGroup.Tpo -c -o ServerListingGroup.o `test -f 'protocol/ServerListingGroup.cpp' || echo '$(srcdir)/'`protocol/ServerListingGroup.cpp
	mv -f $(DEPDIR)/ServerListingGroup.Tpo $(DEPDIR)/ServerListingGroup.Po
#	source='protocol/ServerListingGroup.cpp' object='ServerListingGroup.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ServerListingGroup.o `test -f 'protocol/ServerListingGroup.cpp' || echo '$(srcdir)/'`protocol/ServerListingGroup.cpp

ServerListingGroup.obj: protocol/ServerListingGroup.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ServerListingGroup.obj -MD -MP -MF $(DEPDIR)/ServerListingGroup.Tpo -c -o ServerListingGroup.obj `if test -f 'protocol/ServerListingGroup.cpp'; then $(CYGPATH_W) 'protocol/ServerListingGroup.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/ServerListingGroup.cpp'; fi`
	mv -f $(DEPDIR)/ServerListingGroup.Tpo $(DEPDIR)/ServerListingGroup.Po
#	source='protocol/ServerListingGroup.cpp' object='ServerListingGroup.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ServerListingGroup.obj `if test -f 'protocol/ServerListingGroup.cpp'; then $(CYGPATH_W) 'protocol/ServerListingGroup.cpp'; else $(CYGPATH_W) '$(srcdir)/protocol/ServerListingGroup.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-zip distcheck \
	distclean distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
